### ISSUE TITLE
Existing clang format warnings block submission

### ISSUE THREAD

**Issue by CodingCanuck** [3rdparty/stout#26]
https://github.com/3rdparty/stout/pull/25 's merge is blocked: https://github.com/3rdparty/stout/pull/25

Because of pre-existing formatting warnings on unrelated files: https://github.com/3rdparty/stout/runs/5854519985?check_suite_focus=true#step:4:483

e.g.:
```
./stout-stateful-tally/test/stateful-tally.cc:1:1: error: code should be clang-formatted [-Wclang-format-violations]
#include "gtest/gtest.h"
^
```

We should fix these warnings to unblock submission.

@benh I just checked the "Include administrators" box on stout's [branch protection rules](https://github.com/3rdparty/stout/settings/branch_protection_rules/23654412) to avoid admins accidentally merging broken PRs (per https://github.com/reboot-dev/company/issues/12 ): was that intentionally left unchecked to work around this issue?

**Comment by CodingCanuck** [comment]
@ArthurBandaryk have you been poking at this code recently? Is it quick to do a bulk format? (Not sure if this also requires touching submodules)

**Comment by benh** [comment]
> @benh I just checked the "Include administrators" box on stout's [branch protection rules](https://github.com/3rdparty/stout/settings/branch_protection_rules/23654412) to avoid admins accidentally merging broken PRs (per [reboot-dev/company#12](https://github.com/reboot-dev/company/issues/12) ): was that intentionally left unchecked to work around this issue?

Correct. @ArthurBandaryk might be closer than expected though, and it's not a pain to uncheck, so no worries!
